### PR TITLE
Connect sun-moon animation to global react state

### PR DESCRIPTION
**Pull request by nikolas**
This makes the "Start Animation" button work.

### CODE REVIEW

**Comment by nikolas** [comment]
I've also added the animated moon sprite in the main view here.

**Comment by nikolas** [comment]
I've also added [webpack-serve](https://github.com/webpack-contrib/webpack-serve) to this branch, to solve the issue where loading images causes a CORS error when opening index.html as a `file:///` url. I get around this by using nginx... but it is convenient to not have to set up a real web server just to work on this, and webpack-serve seems to be a good choice since I'm already using webpack. It's only half working though - currently the webpack server still requires a separate webpack command in order for the build to be up to date.

**Comment by sdreher** [comment]
The webpacks hook up the Makefile to `serve`. Could work here as well: https://github.com/ccnmtl/dentalofficelocation-pack/blob/master/Makefile#L29

**Comment by sdreher** [comment]
Animation looks good!

**Pull request merged**
